//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.22 at 09:12:19 PM BST 
//


package artporsh.cockatrice.mycollection.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="set" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="longname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="settype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="releasedate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cards">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="card" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="prop">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                                       &lt;element name="manacost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-commander" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-duel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="coloridentity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-oldschool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="side" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="pt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="colors" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="layout" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-legacy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cmc" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="maintype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-vintage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-pauper" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-frontier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-modern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-penny" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-future" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="format-standard" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/choice>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="set" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="muid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="rarity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="tablerow" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sets",
    "cards"
})
@XmlRootElement(name = "cockatrice_carddatabase")
public class CockatriceCarddatabase {

    @XmlElement(required = true)
    protected CockatriceCarddatabase.Sets sets;
    @XmlElement(required = true)
    protected CockatriceCarddatabase.Cards cards;
    @XmlAttribute(name = "version")
    protected Byte version;

    /**
     * Gets the value of the sets property.
     * 
     * @return
     *     possible object is
     *     {@link CockatriceCarddatabase.Sets }
     *     
     */
    public CockatriceCarddatabase.Sets getSets() {
        return sets;
    }

    /**
     * Sets the value of the sets property.
     * 
     * @param value
     *     allowed object is
     *     {@link CockatriceCarddatabase.Sets }
     *     
     */
    public void setSets(CockatriceCarddatabase.Sets value) {
        this.sets = value;
    }

    /**
     * Gets the value of the cards property.
     * 
     * @return
     *     possible object is
     *     {@link CockatriceCarddatabase.Cards }
     *     
     */
    public CockatriceCarddatabase.Cards getCards() {
        return cards;
    }

    /**
     * Sets the value of the cards property.
     * 
     * @param value
     *     allowed object is
     *     {@link CockatriceCarddatabase.Cards }
     *     
     */
    public void setCards(CockatriceCarddatabase.Cards value) {
        this.cards = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setVersion(Byte value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="card" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="prop">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                             &lt;element name="manacost" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-commander" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-duel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="coloridentity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-oldschool" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="side" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="pt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="colors" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="layout" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-legacy" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cmc" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="maintype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-vintage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-pauper" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-frontier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-modern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-penny" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-future" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="format-standard" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/choice>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="set" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="muid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="rarity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="tablerow" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "card"
    })
    public static class Cards {

        protected List<CockatriceCarddatabase.Cards.Card> card;

        /**
         * Gets the value of the card property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the card property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCard().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CockatriceCarddatabase.Cards.Card }
         * 
         * 
         */
        public List<CockatriceCarddatabase.Cards.Card> getCard() {
            if (card == null) {
                card = new ArrayList<CockatriceCarddatabase.Cards.Card>();
            }
            return this.card;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="prop">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
         *                   &lt;element name="manacost" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-commander" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-duel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="coloridentity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-oldschool" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="side" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="pt" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="colors" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="layout" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-legacy" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="cmc" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="maintype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-vintage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-pauper" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-frontier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-modern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-penny" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-future" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="format-standard" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/choice>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="set" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="muid" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="rarity" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}short" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="tablerow" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "text",
            "prop",
            "set",
            "tablerow"
        })
        public static class Card {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String text;
            @XmlElement(required = true)
            protected CockatriceCarddatabase.Cards.Card.Prop prop;
            protected List<CockatriceCarddatabase.Cards.Card.Set> set;
            protected byte tablerow;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }

            /**
             * Gets the value of the prop property.
             * 
             * @return
             *     possible object is
             *     {@link CockatriceCarddatabase.Cards.Card.Prop }
             *     
             */
            public CockatriceCarddatabase.Cards.Card.Prop getProp() {
                return prop;
            }

            /**
             * Sets the value of the prop property.
             * 
             * @param value
             *     allowed object is
             *     {@link CockatriceCarddatabase.Cards.Card.Prop }
             *     
             */
            public void setProp(CockatriceCarddatabase.Cards.Card.Prop value) {
                this.prop = value;
            }

            /**
             * Gets the value of the set property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the set property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSet().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CockatriceCarddatabase.Cards.Card.Set }
             * 
             * 
             */
            public List<CockatriceCarddatabase.Cards.Card.Set> getSet() {
                if (set == null) {
                    set = new ArrayList<CockatriceCarddatabase.Cards.Card.Set>();
                }
                return this.set;
            }

            /**
             * Gets the value of the tablerow property.
             * 
             */
            public byte getTablerow() {
                return tablerow;
            }

            /**
             * Sets the value of the tablerow property.
             * 
             */
            public void setTablerow(byte value) {
                this.tablerow = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice maxOccurs="unbounded" minOccurs="0">
             *         &lt;element name="manacost" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-commander" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-duel" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="coloridentity" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-oldschool" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="side" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="pt" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="colors" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="layout" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-legacy" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="cmc" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="maintype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-vintage" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-pauper" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-frontier" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-modern" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-penny" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-future" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="format-standard" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "manacostOrFormatCommanderOrFormatDuel"
            })
            public static class Prop {

                @XmlElementRefs({
                    @XmlElementRef(name = "format-commander", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "pt", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "maintype", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "coloridentity", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-standard", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "manacost", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-duel", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "side", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "colors", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-penny", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-modern", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "layout", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-vintage", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-oldschool", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-future", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-frontier", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-legacy", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "cmc", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "format-pauper", type = JAXBElement.class, required = false)
                })
                protected List<JAXBElement<? extends Serializable>> manacostOrFormatCommanderOrFormatDuel;

                /**
                 * Gets the value of the manacostOrFormatCommanderOrFormatDuel property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the manacostOrFormatCommanderOrFormatDuel property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getManacostOrFormatCommanderOrFormatDuel().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<JAXBElement<? extends Serializable>> getManacostOrFormatCommanderOrFormatDuel() {
                    if (manacostOrFormatCommanderOrFormatDuel == null) {
                        manacostOrFormatCommanderOrFormatDuel = new ArrayList<JAXBElement<? extends Serializable>>();
                    }
                    return this.manacostOrFormatCommanderOrFormatDuel;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="muid" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="rarity" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}short" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Set {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "muid")
                protected Integer muid;
                @XmlAttribute(name = "rarity")
                protected String rarity;
                @XmlAttribute(name = "uuid")
                protected String uuid;
                @XmlAttribute(name = "num")
                protected String num;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the muid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMuid() {
                    return muid;
                }

                /**
                 * Sets the value of the muid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMuid(Integer value) {
                    this.muid = value;
                }

                /**
                 * Gets the value of the rarity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRarity() {
                    return rarity;
                }

                /**
                 * Sets the value of the rarity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRarity(String value) {
                    this.rarity = value;
                }

                /**
                 * Gets the value of the uuid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUuid() {
                    return uuid;
                }

                /**
                 * Sets the value of the uuid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUuid(String value) {
                    this.uuid = value;
                }

                /**
                 * Gets the value of the num property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNum() {
                    return num;
                }

                /**
                 * Sets the value of the num property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNum(String value) {
                    this.num = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="set" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="longname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="settype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="releasedate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "set"
    })
    public static class Sets {

        protected List<CockatriceCarddatabase.Sets.Set> set;

        /**
         * Gets the value of the set property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the set property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CockatriceCarddatabase.Sets.Set }
         * 
         * 
         */
        public List<CockatriceCarddatabase.Sets.Set> getSet() {
            if (set == null) {
                set = new ArrayList<CockatriceCarddatabase.Sets.Set>();
            }
            return this.set;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="longname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="settype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="releasedate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "longname",
            "settype",
            "releasedate"
        })
        public static class Set {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String longname;
            @XmlElement(required = true)
            protected String settype;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar releasedate;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the longname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLongname() {
                return longname;
            }

            /**
             * Sets the value of the longname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLongname(String value) {
                this.longname = value;
            }

            /**
             * Gets the value of the settype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSettype() {
                return settype;
            }

            /**
             * Sets the value of the settype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSettype(String value) {
                this.settype = value;
            }

            /**
             * Gets the value of the releasedate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getReleasedate() {
                return releasedate;
            }

            /**
             * Sets the value of the releasedate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setReleasedate(XMLGregorianCalendar value) {
                this.releasedate = value;
            }

        }

    }

}
