//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.22 at 09:12:19 PM BST 
//


package artporsh.cockatrice.mycollection.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the artporsh.cockatrice.mycollection.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CockatriceCarddatabaseCardsCardPropFormatOldschool_QNAME = new QName("", "format-oldschool");
    private final static QName _CockatriceCarddatabaseCardsCardPropSide_QNAME = new QName("", "side");
    private final static QName _CockatriceCarddatabaseCardsCardPropManacost_QNAME = new QName("", "manacost");
    private final static QName _CockatriceCarddatabaseCardsCardPropPt_QNAME = new QName("", "pt");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatFuture_QNAME = new QName("", "format-future");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatDuel_QNAME = new QName("", "format-duel");
    private final static QName _CockatriceCarddatabaseCardsCardPropColoridentity_QNAME = new QName("", "coloridentity");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatModern_QNAME = new QName("", "format-modern");
    private final static QName _CockatriceCarddatabaseCardsCardPropType_QNAME = new QName("", "type");
    private final static QName _CockatriceCarddatabaseCardsCardPropColors_QNAME = new QName("", "colors");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatLegacy_QNAME = new QName("", "format-legacy");
    private final static QName _CockatriceCarddatabaseCardsCardPropLayout_QNAME = new QName("", "layout");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatCommander_QNAME = new QName("", "format-commander");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatVintage_QNAME = new QName("", "format-vintage");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatFrontier_QNAME = new QName("", "format-frontier");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatStandard_QNAME = new QName("", "format-standard");
    private final static QName _CockatriceCarddatabaseCardsCardPropCmc_QNAME = new QName("", "cmc");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatPauper_QNAME = new QName("", "format-pauper");
    private final static QName _CockatriceCarddatabaseCardsCardPropMaintype_QNAME = new QName("", "maintype");
    private final static QName _CockatriceCarddatabaseCardsCardPropFormatPenny_QNAME = new QName("", "format-penny");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: artporsh.cockatrice.mycollection.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CockatriceCarddatabase }
     * 
     */
    public CockatriceCarddatabase createCockatriceCarddatabase() {
        return new CockatriceCarddatabase();
    }

    /**
     * Create an instance of {@link CockatriceCarddatabase.Cards }
     * 
     */
    public CockatriceCarddatabase.Cards createCockatriceCarddatabaseCards() {
        return new CockatriceCarddatabase.Cards();
    }

    /**
     * Create an instance of {@link CockatriceCarddatabase.Cards.Card }
     * 
     */
    public CockatriceCarddatabase.Cards.Card createCockatriceCarddatabaseCardsCard() {
        return new CockatriceCarddatabase.Cards.Card();
    }

    /**
     * Create an instance of {@link CockatriceCarddatabase.Sets }
     * 
     */
    public CockatriceCarddatabase.Sets createCockatriceCarddatabaseSets() {
        return new CockatriceCarddatabase.Sets();
    }

    /**
     * Create an instance of {@link CockatriceCarddatabase.Cards.Card.Prop }
     * 
     */
    public CockatriceCarddatabase.Cards.Card.Prop createCockatriceCarddatabaseCardsCardProp() {
        return new CockatriceCarddatabase.Cards.Card.Prop();
    }

    /**
     * Create an instance of {@link CockatriceCarddatabase.Cards.Card.Set }
     * 
     */
    public CockatriceCarddatabase.Cards.Card.Set createCockatriceCarddatabaseCardsCardSet() {
        return new CockatriceCarddatabase.Cards.Card.Set();
    }

    /**
     * Create an instance of {@link CockatriceCarddatabase.Sets.Set }
     * 
     */
    public CockatriceCarddatabase.Sets.Set createCockatriceCarddatabaseSetsSet() {
        return new CockatriceCarddatabase.Sets.Set();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-oldschool", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatOldschool(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatOldschool_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "side", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropSide(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropSide_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "manacost", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropManacost(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropManacost_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pt", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropPt(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropPt_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-future", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatFuture(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatFuture_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-duel", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatDuel(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatDuel_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "coloridentity", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropColoridentity(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropColoridentity_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-modern", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatModern(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatModern_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropType(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropType_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "colors", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropColors(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropColors_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-legacy", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatLegacy(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatLegacy_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "layout", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropLayout(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropLayout_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-commander", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatCommander(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatCommander_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-vintage", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatVintage(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatVintage_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-frontier", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatFrontier(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatFrontier_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-standard", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatStandard(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatStandard_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cmc", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<Byte> createCockatriceCarddatabaseCardsCardPropCmc(Byte value) {
        return new JAXBElement<Byte>(_CockatriceCarddatabaseCardsCardPropCmc_QNAME, Byte.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-pauper", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatPauper(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatPauper_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maintype", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropMaintype(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropMaintype_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format-penny", scope = CockatriceCarddatabase.Cards.Card.Prop.class)
    public JAXBElement<String> createCockatriceCarddatabaseCardsCardPropFormatPenny(String value) {
        return new JAXBElement<String>(_CockatriceCarddatabaseCardsCardPropFormatPenny_QNAME, String.class, CockatriceCarddatabase.Cards.Card.Prop.class, value);
    }

}
